name=input("enter your name:")
age=input("enter your age:")
ocuupation=input("enter your occupation:")
mobile_number=input("enter your mobile nummber:")
hobbies=input("enter your hobbies:")
intrests=input("enter your intrests:")
print("\n Biodata:")
print("name:",name)
print("age:",age)
print("occupation:",ocuupation)
print("mobile_number:",mobile_number)
print("hobbies:",hobbies)
print("intrests:",intrests)